### ISSUE TITLE
Add method to generated DOB/0 pattern data

### ISSUE THREAD

**Issue by ashuralyk** [sporeprotocol/spore-sdk#107]
# Description
considering there would be so much demands to generate the pattern of DOB/0, we need to provide a web-tool to achieve this. After finishing then, a user-friendly web page should be on the way.

**Comment by ashuralyk** [comment]
due to the compatibility issue in `moleculec-es`: https://github.com/nervosnetwork/moleculec-es/issues/8, this suggestion may block for a while

**Comment by Hanssen0** [comment]
Molecule has been aborted in DOB.
