### ISSUE TITLE
The error messages for checking the type of the target cell need improvement.

### ISSUE THREAD

**Issue by Dawn-githup** [sporeprotocol/spore-sdk#43]
- Using an older version of the SDK cannot transfer the new version of Spore, and the error message needs to be improved.

https://github.com/sporeprotocol/spore-sdk/blob/beta/packages/core/src/api/joints/spore/getSpore.ts#L22C1-L26C4

**Comment by ShookLyngs** [comment]
The error message is to report that the type script of the target cell is not expaected.
Maybe we should add more details to the message:
```markdown
- Cannot find spore by Type because target cell type is not Spore
+ Cannot find spore by Type because target cell type is not Spore or the version is not supported
```

**Comment by ashuralyk** [comment]
@Dawn-githup is this issue still there?

**Comment by Dawn-githup** [comment]
> @Dawn-githup is this issue still there?

Not modified
