### ISSUE TITLE
Automatically test the SDK with GitHub Actions

### ISSUE THREAD

**Issue by ShookLyngs** [sporeprotocol/spore-sdk#47]
We have 2 kinds of tests right now:
- Tests that cost capacity - Can run locally
- Tests that are don't cost capacity - Can run in github actions

@Dawn-githup In order to set up github actions to automatically test the sdk, we need a to address the capacity costing issue.

**Comment by Dawn-githup** [comment]
https://github.com/cryptape/acceptance-internal/issues/561

**Comment by Dawn-githup** [comment]
> We have 2 kinds of tests right now:
> 
> * Tests that cost capacity - Can run locally
> * Tests that are don't cost capacity - Can run in github actions
> 
> @Dawn-githup In order to set up github actions to automatically test the sdk, we need a to address the capacity costing issue.

I considered starting a local node for automated testing

**Comment by Dawn-githup** [comment]
- Create dev node reference:
https://github.com/Dawn-githup/CKB-Contract-Data-Simulator
