### ISSUE TITLE
Rewrite on-chain transaction-related tests

### ISSUE THREAD

**Issue by ShookLyngs** [sporeprotocol/spore-sdk#54]
# Description

Currently, our on-chain transaction-related test cases, such as creating/transferring Spores on the CKB testnet, can only be run locally with manual adjustments. This is hindering our goal of implementing GitHub Automations. Therefore, I'd like to rewrite all the following test cases, focusing on testing the major features of Spore.

# Status
- [x] Rewrite Spore & Cluster basic tests
- [x] Rewrite ClusterProxy & ClsuterAgent tests

# Tests

### Cluster
- Create a Cluster (v2)
- Transfer a Cluster (v2)

#### Basic operations
- Create a Spore
- Transfer a Spore
- Melt a Spore

#### Immortal
- Create an immortal Spore
- Try melt an immortal Spore

#### Referencing Cluster
- Create a Spore with Cluster (v2)
  - via cell reference
  - via lock proxy
- Create a Spore with Cluster (v1)
  - via cell reference

### ClusterProxy

- Create a ClusterProxy with Cluster (v2)
  - via cell reference
  - via lock proxy
- Craete a ClusterProxy with Clsuter (v1)
  - via cell reference
- Transfer a ClusterProxy
- Melt a ClusterProxy

### ClusterAgent

- Create a ClusterAgent with ClusterProxy
  - via cell reference
  - via payment
- Transfer a ClusterAgent
- Melt a ClusterAgent

### Spore

- Create a Spore with ClusterAgent
  - via cell reference
  - via lock proxy

**Comment by ashuralyk** [comment]
running in native denet of CKB requires to rewrite entire test cases?

**Comment by ShookLyngs** [comment]
> running in native denet of CKB requires to rewrite entire test cases?

Mainly, the tests with pre-requirements (e.g., requiring a Spore ID to transfer the Spore) will be rewritten. 
So I think this is focused on automating our tests.

**Comment by ShookLyngs** [comment]
On-chain transaction-related tests have been rewritten in #56.
