### ISSUE TITLE
Automatically search all of Spore cells with different code hashes

### ISSUE THREAD

**Issue by ashuralyk** [sporeprotocol/spore-sdk#83]
# Description

`spore-sdk` current has only one selection to show Spore cells with fixed code hash, but in reality, we are supposed to have more than one versions of Spore cells, and the responsibility to filter them all is on our side not the application layer, so we've got to implement this feature for compatibility use.

maybe I guess, this feature also should be enabled in `spore-graphql` project.

**Comment by ShookLyngs** [comment]
Currently, the spore-sdk doesn't have a list querying api provided, so this restriction does not come from the sdk. From the dapp's side, I think we should take a look at the spore-graphql and see how to support querying multiple versions of the spore/cluster cells.

**Comment by ShookLyngs** [comment]
Follow this issue in the spore-graphql for updates: https://github.com/sporeprotocol/spore-graphql/issues/11
